### ISSUE TITLE
Audio Output to DAC

### ISSUE THREAD

**Issue by roller51** [KenT2/pipresents-next#15]
Pi Presents gives two options for outputting audio -  HDMI or analogue. Is it possible to output audio through a USB DAC/sound card instead? I use one of my Raspberry Pis as a media server/player with audio output to a USB DAC. It has much better sound quality than the native analogue audio jack. I configure the audio ouput to the DAC through the Squeezelite audio player setup. Is this possible with Pi Presents? If not, can it be configured through the OS or perhaps added as a future enhancement  to P Presents.

**Comment by KenT2** [comment]
Investigated this. USB audio cannot be used with omxplayer and hence not for playing video. Best way ahead is to configure Raspbian to use USB instead of analogue audio for mplayer. Since this is unlikely to be a selectable option per track I do not intend to add a selection option to Pi Presents.
