### ISSUE TITLE
Connecting a PIR

### ISSUE THREAD

**Issue by wtpooh89** [KenT2/pipresents-next#21]
Ken:  I am noobie.  Apologies in advance for troubling you with what is probably a basic question.  I am trying to harmonize the directions in your manual for pipresents-next for connecting a PIR sensor with the directions provided for the Adafruit PIR to connect to an RPi  https://learn.adafruit.com/downloads/pdf/pir-passive-infrared-proximity-motion-sensor.pdf    Your manual refers to "PIR's should have Normally Closed relay contacts and be connected between the GPIO pin and 0 volts."  Not sure how to connect to "0 volts"  The Adafruit PIR requires connecting the Ground wire to Ground, Power wire to 5 volts and Signal (output 3.3 volts) to the GPIO.  Will these instructions work with PiPresents as long as I connect the signal to GPIO 11 rather than GPIO 7?  Thanks.

**Comment by KenT2** [comment]
Fixed in Version 1.3 (pipresents-gapless)

**Comment by wtpooh89** [comment]
Thanks for letting me know.  I look forward to checking it out.

Marty
