### ISSUE TITLE
No sound, no editor

### ISSUE THREAD

**Issue by strataca** [KenT2/pipresents-next#23]
Hi Ken
Got pp next downloaded and running, and your examples also. I have no audio. I am rumming on HDMI to a TV. Audio is on and turned up on the TV. Tried opening Qjack audio on the pi with nothing. I am using the SUits trailer as a test tool. I am assuming there is audio to it. Running it through pp_menu. I suppose there is a simple setting I am missing would you help please. 

ALso I can not run editor using python pp_editor.py it says no such file. WHat do I need to download again to get this. 
Thanks a bunch.

**Comment by KenT2** [comment]
On 26/01/2015 19:29, strataca wrote:
>
> Hi Ken
> Got pp next downloaded and running, and your examples also. I have no 
> audio. I am rumming on HDMI to a TV. Audio is on and turned up on the TV. 
> Tried opening Qjack audio on the pi with nothing. I am using the SUits 
> trailer as a test tool. I am assuming there is audio to it. Running it 
> through pp_menu. I suppose there is a simple setting I am missing would 
> you help please.
>
PP should be set to use HDMI out of the box. Try typing  omxplayer -o hdmi 
suits-short.mkv from the pi presents media directory to eliminate PP. If 
this fails to produce sound there is something wrong between your tele and 
the Pi. When I was reviewing PiTouch I found that I had to edit config.txt 
to make HDMI_DRIVE=2. This made the sound work. Seems some tele's need it 
others do not.

> ALso I can not run editor using python pp_editor.py it says no such file. 
> WHat do I need to download again to get this.
> Thanks a bunch.
>
Are you trying to run it from the pipresents directory?  Is the file 
pp_editor.py in the pipresents directory. If not I don't know why as it is 
one of the many files you downloaded from Github. Its on the code tab if you 
need it.

**Comment by strataca** [comment]
This seems to be an odd ball TV so I will try that.

I was in the home directory when I tried editor, so I will try switching to the PP directory. 
Thanks for clearing that up.
