### ISSUE TITLE
Download Pi Presents Installation -O

### ISSUE THREAD

**Issue by Sensebellum** [KenT2/pipresents-next#24]
I am having trouble getting Pi Presents to install correctly. I get everrything right and then am hung up on this line:

     wget https://github.com/KenT2/pipresents-next/tarball/master -O - | tar xz

the -O does not want to run. I get this error:

wget invalid option -- 'O'
gzip: stdin: not in gzip format
tar: child returned status 1
tar: error is not recoverable: exiting now

What's going on? How do I get around this? I am new to the terminal but have some skills. I have obviously tried a zero, a lower case, etc. Any suggestions?

**Comment by Sensebellum** [comment]
I tried it without the -O and I got this error at the bottom:

gzip: stdin: not in gzip format
tar: child returned status 1
tar: error is not recoverable: exiting now

**Comment by KenT2** [comment]
Command looks OK to me and its been used by many people without problems, I suspect a corrupt download. Did you sort it or use the download zip file method.

**Comment by Sensebellum** [comment]
I used the zip file because this line would not execute after many attempts.

wget https://github.com/KenT2/pipresents-next/tarball/master -O - | tar xz

It said the letter -O was not making any sense

**Comment by KenT2** [comment]
Tried it on my Pi, worked fine.
