### ISSUE TITLE
Better way to Exit Program

### ISSUE THREAD

**Issue by Sensebellum** [KenT2/pipresents-next#25]
After using this a while it is becoming clear that there could be a better way to exit the program.

I get stuck in full screen mode or stuck with the video so many times I usually have to unplug it and try again. I try all the key combinations and none of them will exit. Why is that?

It would be nice to just hit the esc key once and have that be that.

Can this be a feature please?

**Comment by jimbogr77** [comment]
Ctrl + break. It is written on the manual.

**Comment by Sensebellum** [comment]
I know, I read that and it still doesn't work. 

Plus, a lot of keyboards do not have that key anymore

**Comment by jimbogr77** [comment]
Sorry can't help you more. It was the only way I used.

Try to use a "quit" button that has a wrong mediashow link in order to make the app crash. It should work.

**Comment by Sensebellum** [comment]
That's actually what I sort of ended up coming up with anyways. Good show none the less

**Comment by KenT2** [comment]
1. Escape in a mediashow stops the current track. If the mediashow is not set to manual it will start the next track so its not the right way to abort PP.

2. CTRL BREAK should always work whatever PP is doing. However if omxplayer is crashing when playing  a video CTRL BREAK sometimes does not work. Using the terminal use CTRL-C if that does not work use CTRL-Z. That usually works but can leave omxplayer running. Use killall omxplayer omxplayer.bin  to kill the sub-processes. Even then you  sometimes get zombie omxplayers and you need to close the terminal window to get rid of them. Use top -upi to see what is going on.

 If you have had lots of omxplayer crashes the Pi seems to get into a funny state. Its often best to shutdown and resstart.

3. window videos while developng applications by using warp so you can see what i going on.

4. You can define alternatives to CTRL-BREAK in keys.cfg.

5. That you cannot use Control_F1 after uncommenting it looks like a bug in keys.cfg

The - should be an _ see here http://effbot.org/tkinterbook/tkinter-events-and-bindings.htm

<Control_F1> = pp-exit

**Comment by Sensebellum** [comment]
I understand the role of esc now.

I found that I was able to press alt-F4 and it would exit the program right away.

**Comment by KenT2** [comment]
That's useful . it appears alt-f4 is the standard linux keyboard shortcut for pressing the close button (X) on a window. I'll add it to the manual in the next version.

**Comment by Sensebellum** [comment]
Good stuff, glad that could help!

**Comment by KenT2** [comment]
Corrected keys.cfg

**Comment by KenT2** [comment]
Reverted change to keys.cfg <Control-F1> was correct.
