### ISSUE TITLE
Instructions for Auto Start may not work

### ISSUE THREAD

**Issue by Sensebellum** [KenT2/pipresents-next#26]
What is a proven way to auto start PiPresents?

I followed the instructions in the manual to the T but these did not launch the program.

I have tried about 4 other methods including rc.local and not one will launch the Pi Presents profile.

Why is this? How has everyone else been doing it? We wrote the profile in a few hours and have spent the past 2 days trying to get it to launch when power is applied to the Pi.

Please, any tips are extremely welcome.

Here is my command:
sudo python /home/pi/pipresents/pipresents.py -o /home/pi -p Kisok -f -b -g

It works when I put it in Terminal but it will not autorun in any configuration I have tried. This is really the clincher to making this useful. We can't have a librarian running around to all 30 installation with a wireless keyboard using terminal to start these up.

**Comment by KenT2** [comment]
Possibly this change to LXDE

https://pipresents.wordpress.com/news/

**Comment by Sensebellum** [comment]
Many, many, many thanks KenT2!!

This would be an excellent tip to add to the manual.

Appending that "-pi" to the LXDE worked nicely

I think this project is finally ready to roll!

**Comment by KenT2** [comment]
Added to manual
