### ISSUE TITLE
Pipresents Examples Errors

### ISSUE THREAD

**Issue by dearsgroup** [KenT2/pipresents-next#27]
I am currently testing your product and have run into a few glitches.  Thanks for any assistance.

![error1b](https://cloud.githubusercontent.com/assets/13010259/8758396
/7e51aaf2-2c98-11e5-9ea9-7334b67a6c52.JPG)
![editor](https://cloud.githubusercontent.com/assets/13010259/8758395/7e51174a-2c98-11e5-8fed-d50c2a92f959.JPG)
![error1](https://cloud.githubusercontent.com/assets/13010259/8758397/7e525dd0-2c98-11e5-8222-7817c70aefa0.JPG)
![error1a](https://cloud.githubusercontent.com/assets/13010259/8758398/7e5597ac-2c98-11e5-99f1-c605760676cd.JPG)

**Comment by KenT2** [comment]
not possible to see error1b. error report might be because you are double clicking on an item in the medialist pane.

imageplayer error report suggests that transmission of the image file was interrupted. Which image failed and where are you reading it from.

**Comment by dearsgroup** [comment]
I think you're saying that error1b is not visible.  I thinks it's the image above...let me check. Re-attach just-in-case.
![error1b](https://cloud.githubusercontent.com/assets/13010259/8763746/7b5d6c0e-2d61-11e5-86c7-803d6149be8c.JPG)

**Comment by KenT2** [comment]
Another example of an IO error on using an image file.

googling 'python pil IOerror image file is truncated' suggests the image file is corrupted in some way.

if you have eliminated problems with network, USB stick etc.by placing the file on the SD card then image corruption seems the most likely.

**Comment by dearsgroup** [comment]
Problem solved. Thanks!  Although I can view the pics on my WIn7 box somehow a corruption occurred going to or writing to the pi.  This baffled by all that.  Anyway, I reloaded and am very pleased with the performance now with media show and liveshow (the ones I'll likely use most) during further testing.  Appreciate the quick response and feedback.

**Comment by KenT2** [comment]
That's good. I noticed one of the images was much larger than the likely screen size. You may get PP to load the image faster if, offline, you reduce its size to the size of the screen..

**Comment by dearsgroup** [comment]
Not sure what to make of the following so why not ask.  My Pi is running your product just nicely now.  There is only one something that's a bit confusing for me now.  I typically VNC into the pi now and double-click on a desktop shortcut I've created to run a liveshow.  The show begins and shows static images on the VNC through an LXterminal window but my sample video does not; it only plays on the directly connected hdmi device (in this case a projector).  When the video is finished playing the process repeats.  For some unknown reason the pi will not boot into desktop mode even though I raspi configured it to do so.  I can SSH into it as well.  ??

**Comment by KenT2** [comment]
On 20/07/2015 18:42, DEARS Group LLC wrote:
>
> Not sure what to make of the following so why not ask. My Pi is running 
> your product just nicely now. There is only one something that's a bit 
> confusing for me now. I typically VNC into the pi now and double-click on 
> a desktop shortcut I've created to run a liveshow. The show begins and 
> shows static images on the VNC through an LXterminal window but my sample 
> video does not; it only plays on the directly connected hdmi device (in 
> this case a projector). When the video is finished playing the process 
> repeats.
>
Video is played directly to the Pi's screen by the Pi's GPU. Other content 
is played via Xwindows and is therefore accessible over VNC.

> For some unknown reason the pi will not boot into desktop mode even though 
> I raspi configured it to do so. I can SSH into it as well. ??
>

Not sure what you mean. To get SSH to display stuff on the Pi's screen you 
need to export the display. I'm trying to understand this at the moment. The 
attached script will run Pi Presents profile from a remote Linux computer.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/KenT2/pipresents-next/issues/27#issuecomment-122964504>.
>
> No virus found in this message.
> Checked by AVG - www.avg.com <http://www.avg.com>
> Version: 2015.0.6081 / Virus Database: 4392/10271 - Release Date: 07/20/15
>


ssh pi@192.168.1.102  <<EOF
export DISPLAY=:0
cd pipresents
python pipresents.py -p guest  &
sleep 30
pkill -f pipresents.py
EOF

**Comment by dearsgroup** [comment]
Hmm? I think the issue is with VNC somehow. I created a new image with only Raspbian & Pi Presents on it.  It played without a glitch on my HD Projector.  Disregard my previous concern.  This solution will work best for now.  Thanks.
