### ISSUE TITLE
Auto-Hiding Links?

### ISSUE THREAD

**Issue by aaronjeline** [KenT2/pipresents-next#28]
Is there any way to have links (the ones in the hyerlink show) auto hide?

**Comment by KenT2** [comment]
Not sure what you mean.

if you mean do not show a link on a particular page then just omit the symbolic name of the link from the Controls field of the page.
If you have defined the links in the Controls field of the show so it appears in all pages of the show then you can remove it in a particular page with 'mysymboliclink null'

**Comment by aaronjeline** [comment]
I'm using the links as the control mechanism for a museum slide show. I want the slides to auto-rotate, and I also want a tour guide to be able to pause the show via the touch screen, as well as manually advance and retreat. This works great with links and it was rather easy to set up. In a perfect world, there would be a way to make the links disappear unless the screen was tapped so they aren't distracting. I've made them small and unobtrusive, so it's not the end of the world if this isn't possible.

**Comment by KenT2** [comment]
Thanks.I see what you mean now. There is no way I can think of to do what you want.

As an aside. [pipresents-gapless] will allow click area to be used in any type of show including a mediashow. Also click areas can now be images which might look nicer.

**Comment by dearsgroup** [comment]
Very well. Thanks for now.
