### ISSUE TITLE
Question about Version 1.3 vs 1.2

### ISSUE THREAD

**Issue by John37m** [KenT2/pipresents-next#30]
Hello and thank you for writing the Pi Presents code. I work for the University of Florida Physics Dept and we have a small hands on science demonstrations museum in our lobby. I'm trying to use Pi Presents Next to create a slideshow that runs in a loop but when a guest presses a button to start the experiment running I'd like to interrupt the main slideshow and show a different (child or subshow) slideshow that explains what is happening. Once the second subshow finishes when the experiment ends, I'd like to go back and continue with the main slideshow. I read in your change log that the beta version 1.3 has an "Enhanced - All shows now have their own controls instead of inheriting from their parent. This allows, for example, mediashows which are subshows of hyperlinkshows to have controls. controls.cfg is redundant and has been removed." To do what I want to accomplish with my shows do I need version 1.3 so that the main show runs until the visitor presses a button that would start the subshow, once the subshow ends it defaults back to the main show? Sorry, I left this same question on another issue before i figured out how to create a new category. Thank you. John Mocko

**Comment by KenT2** [comment]
Hi John

Sorry for delay; I've been on holiday.

You are OK with version 1.2. You need to use a Child Show which is a special 
type of subshow. See the pp_interactive example profile.

You are OK because the main show and subshow both require the same set of 
operations.  Whereas something like a mediashow as a subshow of a 
hyperlinkshow needs a different set of operations.

Regards
Ken

**Comment by John37m** [comment]
Thank you, we have figured out the show with version 1.3. Basically we have a master slideshow with a child show. The master runs in a loop until it senses a Pp-play signal from the Gpio which triggers the child show set of slides that run once and then it defaults back to the master show. In the child show we have one slide drive a motor on, it then triggers another show with show control to sense a switch to turn the motor off. A short time later another show control signal triggers another show to run the motor and look for another switch to turn it back off again. Once the sequence finishes it falls back to the master show. The one thing I would request would be to include a track type called "animation" as a possible choice because we had to use a fake audio track with no audio file loaded to drive sections of the show with animation. It would nice to just be able to select a track type of animation directly. That said the program is perfect for our needs and I thank you very much. The device we are driving is a pendulum wave demo built in dedication to a faculty member who passed away and it will become part of our interactive lobby demonstration museum for children.

Hope you had a nice vacation.

John Mocko

Sent from my iPhone

On Aug 14, 2015, at 3:14 PM, KenT2 <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi John

Sorry for delay; I've been on holiday.

You are OK with version 1.2. You need to use a Child Show which is a special
type of subshow. See the pp_interactive example profile.

You are OK because the main show and subshow both require the same set of
operations. Whereas something like a mediashow as a subshow of a
hyperlinkshow needs a different set of operations.

Regards
Ken

On 03/08/2015 14:33, John37m wrote:
>
> Hello and thank you for writing the Pi Presents code. I work for the
> University of Florida Physics Dept and we have a small hands on science
> demonstrations museum in our lobby. I'm trying to use Pi Presents Next to
> create a slideshow that runs in a loop but when a guest presses a button
> to start the experiment running I'd like to interrupt the main slideshow
> and show a different (child or subshow) slideshow that explains what is
> happening. Once the second subshow finishes when the experiment ends, I'd
> like to go back and continue with the main slideshow. I read in your
> change log that the beta version 1.3 has an "Enhanced - All shows now have
> their own controls instead of inheriting from their parent. This allows,
> for example, mediashows which are subshows of hyperlinkshows to have
> controls. controls.cfg is redundant and has been removed." To do what I
> want to accomplish with my shows do I need version 1.3 so that the main
> show runs until the visitor presses a button that would st art the
> subshow, once the subshow ends it defaults back to the main show? Sorry, I
> left this same question on another issue before i figured out how to
> create a new category. Thank you. John Mocko
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/KenT2/pipresents-next/issues/30>.
>
> No virus found in this message.
> Checked by AVG - www.avg.com<http://www.avg.com> <http://www.avg.com>
> Version: 2015.0.6086 / Virus Database: 4392/10419 - Release Date: 08/11/15
>


-

**Comment by KenT2** [comment]
Probably the most complex animation using PP I have heard of. If you happen to do a video of it then I would love to link to it from the PP blog.  Having a special animation track is additional set of  code to maintain. I designed the audio track so it could be used for animation just as you described.

**Comment by John37m** [comment]
It will be October before the display gets its official dedication ceremony and placed in our lobby but I'll post you an HD video link when it does. In the meantime the device looks very much like the link below because we copied Arizona States design (with permission) and improved it with a computer driven code and video display thanks to Pi Presents and a Raspberry Pi. The device will be on display in the lobby of the Physics building at the University of Florida and will join our other lobby displays....


Arizona State's video of the design that we have since improved upon.....


https://www.youtube.com/watch?v=YyTwl-BPs7A


Our other lobby displays that it will join...


http://www.phys.ufl.edu/department/exhibits.shtml


We may also use Pi Presents to drive some of our current displays or future ones. Thank you again!



John



_________________________________________________________________________________________

John Mocko
Senior Teaching Laboratory Specialist (Lecture Demonstrations)
Department of Physics
University of Florida
Gainesville, Fl.
________________________________
