### ISSUE TITLE
Delay between two videos

### ISSUE THREAD

**Issue by goktugerce** [KenT2/pipresents-next#35]
Hello,

I started using pipresents-next but I have a problem. It takes 1-2 seconds to make a transition between two videos. I searched for a parameter in options for this but couldn't find anything. Is there a reason for it or can it be fixed by me?

**Comment by KenT2** [comment]
The reason is that the Pi (omxplayer) takes 1-2 seconds to start a video.
 Pipresents gapless pauses a video at the end to cover the gaps,  Also artmediashows and artliveshows preloads the next video  to give gapless and pauseless playback, but have limited control functionality
