### ISSUE TITLE
New to this....

### ISSUE THREAD

**Issue by TonyO511** [KenT2/pipresents-next#38]
Hi, I am really new to this and have a few questions...First, is pi presents defunked? I can't seem to find any current issues, everything seems to be at least a year old or older. My problem is, I'm trying to download pi presents to my rasberry pi. When I type in https://github.com/KenT2/pipresents-next/tarball/master -O - | tar xz...it looks like it is downloading, but everything comes up saying cannot open; no such file permission denied.  I can't seem to find anything addressing this problem. Can someone please guide me in the right direction? Thanks in advance.....

**Comment by KenT2** [comment]
Pi Presnts - next is the stable version and will have no updates other than bug fixes. PiPresents Gapless is the development version.
Your command looks OK. YOu can download the zip file from Github as an alternative method of installation.

**Comment by TonyO511** [comment]
Thanks for your reply Ken....finally got it to run, but having other issues with it. Still trying to learn it, probably something simple I'm over looking. I do have another question though, I read somewhere that it is or was to be able to run from a windows pc, did that ever come to light or is that not possible....just curious...thanks again..

**Comment by KenT2** [comment]
Only the editor will run from a Windows PC.
