### ISSUE TITLE
GPIO inputs not working

### ISSUE THREAD

**Issue by gazmac52** [KenT2/pipresents-next#39]
I must be doing something wrong. No matter what I try I cannot get switches to pause or play pipresents.
I have tried many example files. Even tried version 1.2 but no joy.
The manual says to install a N.O. switch between ground and appropriate pin. This I have done.
Is there something I am missing?
This is my first experience with RPi. Bought a new Pi 3 with NOOBS.
Any suggestions would be gladly received.

**Comment by KenT2** [comment]
To make gapless work you need to a gpio.cfg file in the pp_io_config directory. Also you may need to preface  the python command with sudo. Pi Presents uses physical pin numbers.

or pp-next the python command needs the -g option and gpio.cfg is in a different sub-directory

To test GPIO isolated from PiPresents there is a simple program called input_test.py in the pipresents folder. Instructions in the file.

I have not ever used NOOBS so do not know if there is something special you have to do with NOOBS to enable GPIO
