### ISSUE TITLE
Looping a single video or music file

### ISSUE THREAD

**Issue by drstibnite** [KenT2/pipresents-next#40]
Hi I have managed t get pipresents installed and running using a version of media show, trying to build 2 devices - apologies if this is in the wrong place

1 an old analogue phone that plays a music/audio track when picked up and stops when the handset is replaced. I can get this running so it work when you pick up but I cant get it to stop on a second input even using a holding image as a "next track" with a single track into loop it shows "waiting for input press down cursor to continue"
1. a pi touchscreen which starts a video when you scan a bar code. I have the start working OK and this can run to the end but I cant get past the same "waiting for input ... screen"

interval is set to 0

Is there a way to skip this screen? I was thinking of using a GPIO input tied to ground to simulate a cursor but seems a sledgehammer to crack a nut?

**Comment by KenT2** [comment]
Telephone
In pipresents-gapless the mediashows have been greatly changed to allow this to be done easily.

 It may be possible to do this with pp-next using a radiobuttonshow with a single track. Lifting the phone plays the track and  replacing it stops the track and returns to the 'first' track. You  can use the same gpio fo both just add two symbolic names one for each edge.

Touchscreen
I assume you have arranged the bar code to flip a gpio. Should be OK with a single shot mediashow.
pp-exhibit-1p2 example is of this
