### ISSUE TITLE
How do you target files from a USB drive? What if you don't know video names in advance?

### ISSUE THREAD

**Issue by sjl2024** [KenT2/pipresents-next#41]
Eyeing PiPresents as a potential solution for a headless auto video looper. It looks promising for this. For my use case 1) I won't know the name of the video to autoloop (just that it will only ever be one video at a time) and 2) the video will reside on a thumbdrive as that is the most flexible way for my client to transfer update it painlessly (at their disposal).

Is PiPresents able to handle both of those scenarios? I have seen some other intriguing code which will autolaunch a script at startup (see step 2 [here](https://global.gotomeeting.com/join/613796245). I'd like that script to be a PiPresents script! As long as it can meet my prerequisites.

Thanks!

**Comment by KenT2** [comment]
Can do, use a liveshow
