### ISSUE TITLE
Video trigger by PIR (oneshot) plays video twice at same time

### ISSUE THREAD

**Issue by slingshotdev** [KenT2/pipresents-next#47]
I have a mediashow configured to play a single video (MP4) that is triggered by an attached PIR.
It works great, but if the PIR is triggered after the video plays another omxplayer instance is started and plays the video again over the top of the first instance giving me a flicking display showing the first and second instance of video at the same time.

What am I doing wrong?

**Comment by KenT2** [comment]
You are doing nothing wrong. It is likely that the PIR is triggering twice in quick succession.

If you increase the threshold for the pin  in gpio.cfg that cured it for another user. 

If that fails tell me as I have a better solution which requires additional code which I would implement in gapless.

**Comment by slingshotdev** [comment]
Thanks Ken - been doing some more testing. What's strange is that I have two Raspberry Pis configured - using the same model PIR, both using the same profile, but one plays a longer MP4 video than the other.
The device with the shorter video works as desired. PIR triggers the video, video plays, and no matter how many times i trigger the PIR only one instance plays.

On the Pi that is playing the longer video, when triggered it plays as expected, but no matter how long a delay I wait 30secs - 5mins+, if I trigger the PIR again an further instance of the video plays on top of the last.

If I list processes I see a 2nd omxplayer process has started.

The videos are 1hr22m44s @ 3GB and 12m9s @ 63.3MB respectively. If I set both PIs to play the shorter Video I don't see another omxplayer instance start if I trigger the PIR during playback.

Any ideas?

**Comment by KenT2** [comment]
Apart from the video file are the two profiles identical?
What happens if you play the long video on the PI that works with the short video. Do you get double triggering? 

I cannot think what the problem might be. Could you run PP with the -d option (for debugging) and send me the debug file showing the problem.

The part of PP that is causing problems was rewritten in pipresents-gapless. You could give that a try. You will need to alter the profile, the example pp_exhibit_1p3 should do what you want.

**Comment by slingshotdev** [comment]
Sorry for the delay in update on this. I ended up replacing the PI that had the issue with a V3 (it was V2) and the problem went away. Had to get it to the customer so didn't spend any more time fault finding. Only thought is that with the larger file it took longer to start to stream on the lower spec PI so omxplayer was started again.

Anyway. All working now - thanks! Here it is in situ. Built it in a case so the customer could self install easily.
![image](https://user-images.githubusercontent.com/20046539/31069428-574b3eda-a754-11e7-8300-1b01a7bdb5af.png)

**Comment by KenT2** [comment]
I have tried to recreate your problem on a Pi 3 and a slower B+ using pp-next and pp-gapless with no success.

I used the_graduate.mp4 which is 1.4GB also big-buck bunny.avi 

The only thing I noticed was that a .avi file loads much slower than the same .mp4 file, but that is not your problem.

I wonder if your profile is wrong in some way. If you contact me on pipresents wordpress I will email my address so you can send it to me.
