### ISSUE TITLE
Install instructions fail on "stretch"

### ISSUE THREAD

**Issue by NumerousHats** [KenT2/pipresents-next#49]
In my hands, "sudo apt-get install pexpect" fails with "Unable to locate package pexpect". I am on a Raspberry Pi 3 running Raspbian 9 (stretch). Please let me know if you need any other information about my system.

I am new to Raspberry Pi, and I just started playing with Pi Presents a few days ago. I was able to install it fine, but today I tried it again on a fresh SD card, and it failed. I thought I was losing my mind, but I just realized that in the meantime there had been a commit that changed the installation instructions...

Phenomenal software, BTW! I'm evaluating it for use in an upcoming exhibit :-)

**Comment by KenT2** [comment]
Doh, it should have been python-pexpect

**Comment by NumerousHats** [comment]
_That_ would explain it...

Thanks!
