### ISSUE TITLE
Start Web Editor without Internet

### ISSUE THREAD

**Issue by Peter-Brown-1** [KenT2/pipresents-next#50]
Hi Ken,

I'm sure that this is a bit of a silly one but how do I start the Editor when the Pi is not connected to the internet?

I just get the message 'Waiting for network' and then it times out.

Thanks,
Pete

**Comment by KenT2** [comment]
Hopefully you are using gapless not next, solution is here

https://github.com/KenT2/pipresents-gapless/issues/52

**Comment by Peter-Brown-1** [comment]
Thanks Ken thats sorted it!

Pete
