### ISSUE TITLE
Use mouse to start show?

### ISSUE THREAD

**Issue by CSB1945** [KenT2/pipresents-next#51]
I am working as a volunteer in a small museum.  I am very impressed by your software and am trying to use it to run a single video for an exhibit.  I would like to trigger the video with a mouse click anywhere on the screen and have it run once and go back to the start and wait for another click.  Is this possible?  I have tried several things and read the manual -- probably not as thoroughly as I should -- but can you tell me if it is possible or do I have to wire GPIO to do it?  I have a usb mouse pad I was planning to use.

Thanks for any help you can give.

Scott

**Comment by KenT2** [comment]
You need to use a  click area which covers the whole screen. See the example pp_hyperlinkshow_1p2

in pp-next click areas are limited to hyperlinkshows, in pp-gapless they can be used for any type of show including mediashow triggers which may suit you better

**Comment by CSB1945** [comment]
Sorry to be so long in replying.  I was able to get it to work with a track pad/mouse activating with Button-1 assigned to stqrt the video show.

Now I want to use a physical button.  I have tried using GPIO 18, but it's not working for me.  I suspect I have not set some parameters correctly.  I did get gpio.cfg and put in the profile pp_io_config folder with the keys.cfg file.  This folder is in my profile folder for the show.  I am not sure I have the pin configured correctly and I am very fuzzy on what else should be entered in the show parameters for trigger parameters, trigger and controls.  I have read the manual but would appreciate whatever advice you can give me on setup.  For your information I am working at the Old Independence Regional Museum in Batesville AR as an unpaid volunteer IT person.

Thanks in advance for any help you can give.

Scott

**Comment by KenT2** [comment]
in gpio.cfg:

[P1-18]
direction = in
rising-name =
falling-name = PIR
one-name = 
zero-name = 
repeat = 
threshold = 2
pull-up-down = up

This will work for a push button connected to 0 volts as falling is change from +3.3volts to 0 vollts

if you are using a mediashow then 'trigger for start' should be set to input and the 'Trigger for start parameter' should be PIR

The example pp_exhibit_1p3 implements this using pin p-18 so it should work if you have wired up the Pi correctly.
