### ISSUE TITLE
Is Pi Zero supported?

### ISSUE THREAD

**Issue by NicksonYap** [KenT2/pipresents-next#55]
Hi,

Just before I buy a Pi specially for this, has any one tested video playback on Pi Zero?

Thanks!

**Comment by KenT2** [comment]
Just tried it and video playback works fine as it is implemented by the gpu which is the same for all Pi's I believe. However the time to load videos to start Pi Presents  etc is increased considerably and, as a development machine the Zero is not pleasant.

**Comment by NicksonYap** [comment]
Nice, that's probavly good news
I suppose using Pi 2/3 for dev 
and then Zero for lower cost implementation should be fine

**Comment by KenT2** [comment]
See updated comment above, also response to user  inputs is slower with zero
Unless you are on a really tight budget then I would go with a Pi3 for implementation. By the time you add in cost of power supply, monitor etc.there is not so much difference.

**Comment by NicksonYap** [comment]
Yeah, just worried about performance but I think it makes sense that the cost would be a small difference.
Would probably go for Pi 2/3, but good to know it works for Zero!
