### ISSUE TITLE
Pipresents freezes RPi3A+

### ISSUE THREAD

**Issue by jamesagada** [KenT2/pipresents-next#56]
I am trying to run PiPresents Gapless on a RPI3A+.
When I try to run the example pp-mediashow_1p3, the entire RPi freezes. I cannot even ssh in and have to cut the power. 
When I ran with gpu mem of 16, pipresents will start up and show the mountain pictures but then hang because omxplayer did not start. When I increase the gpu mem to 128, my entire RPi freezes.

**Comment by KenT2** [comment]
I assume you are using Buster Legacy not Bullseye and  PP-gapless even though you have posted in the Next github

I do not have a 3A+ to try but I have just tried on my Pi4 to get a feel for what you need to run PP. You need at least 64MB gpumem for omxplayer. At this value the first video track will play but freeze at the end. To stop the freezing I needed to increase gpumem to 128.

The reason for the freezing is that to get the gapless efffect PP pauses the first video at its end while it loads the second video so 2 copies of omxplayer are briefly running. You can stop this overlap by setting 'Freeze at End' to no in the first video track and so get back to 64 gpumem..

On the Pi4 the RAM usage when PP is playing a video track is 370MB so I would expect the 512MB Pi3a+ to cope. Running Chromium browser at the same time as PP increases RAM usage to 520MB. So closing down any other programs other than PP might help.

Tell me how you get on.

**Comment by jamesagada** [comment]
Thanks. Changed toRPI3b+ and I am cool. RPi3A+ at 512MB is not suitable especially when there are other apps running.
